{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stderr",
     "text": [
      "Using TensorFlow backend.\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "from keras.preprocessing.image import ImageDataGenerator \n",
    "# https://keras.io/api/preprocessing/image/#image-data-preprocessing\n",
    "from keras.applications.imagenet_utils import preprocess_input\n",
    "\n",
    "from keras.applications.vgg16 import VGG16\n",
    "\n",
    "from keras.models import Model\n",
    "\n",
    "from keras.layers import Dense, Flatten\n",
    "\n",
    "from keras.optimizers import Adam\n",
    "from keras.losses import binary_crossentropy\n",
    "from keras.metrics import accuracy\n",
    "\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "49e2ac93",
   "metadata": {},
   "source": [
    "Verificando si las carpetas necesarias estan disponibles"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "dc31cfbe",
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "OK\n"
     ]
    }
   ],
   "source": [
    "pathTrain = './dataset/catdog/train'\n",
    "pathTest = './dataset/catdog/test'\n",
    "\n",
    "if (os.path.exists(pathTrain) and os.path.exists(pathTest)):\n",
    "    print('OK')\n",
    "else:\n",
    "    print('No existen carpetas')\n",
    "    print('Descomprima el archivo catdog.zip o puede descargar otro dataset: https://www.kaggle.com/arpitjain007/dog-vs-cat-fastai')\n"
   ]
  },
  {
   "source": [
    "Crear un generador de nuevas imagenes"
   ],
   "cell_type": "markdown",
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "Found 400 images belonging to 2 classes.\nFound 20 images belonging to 2 classes.\n"
     ]
    }
   ],
   "source": [
    "images_increased = 5\n",
    "width_shape = 224\n",
    "height_shape = 224\n",
    "batch_size = 32\n",
    "\n",
    "train_datagen = ImageDataGenerator(\n",
    "    rotation_range=20, # rota 20 grados\n",
    "    zoom_range=0.2, # zoom\n",
    "    width_shift_range=0.1, # desplazar 10%\n",
    "    height_shift_range=0.1,  # desplazar 10%\n",
    "    horizontal_flip=True, # invertir horizontalmente\n",
    "    vertical_flip=False,\n",
    "    preprocessing_function=preprocess_input\n",
    ")\n",
    "\n",
    "valid_datagen = ImageDataGenerator(    \n",
    "    rotation_range=20,\n",
    "    zoom_range=0.2,\n",
    "    width_shift_range=0.1,\n",
    "    height_shift_range=0.1,\n",
    "    horizontal_flip=True,\n",
    "    vertical_flip=False,\n",
    "    preprocessing_function=preprocess_input)\n",
    "\n",
    "train_generator = train_datagen.flow_from_directory(  \n",
    "    pathTrain,\n",
    "    target_size=(width_shape, height_shape),\n",
    "    batch_size=batch_size,\n",
    "    class_mode='binary')\n",
    "\n",
    "validation_generator = valid_datagen.flow_from_directory(  \n",
    "    pathTest,\n",
    "    target_size=(width_shape, height_shape),\n",
    "    batch_size=batch_size,\n",
    "    class_mode='binary')"
   ]
  },
  {
   "source": [
    "Crear modelo"
   ],
   "cell_type": "markdown",
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "inputShape = (height_shape, width_shape, 3)\n",
    "\n",
    "\n",
    "model = VGG16(include_top=False, weights=\"imagenet\", input_shape=inputShape)"
   ]
  },
  {
   "source": [
    "Configurar capas para no se entrenadas"
   ],
   "cell_type": "markdown",
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stderr",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-18-639816ee340d>\", line 1, in <module>\n",
      "    print(model.layers.shape)\n",
      "AttributeError: 'list' object has no attribute 'shape'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "ERROR! Session/line number was not unique in database. History logging moved to new session 93\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-18-639816ee340d>\", line 1, in <module>\n",
      "    print(model.layers.shape)\n",
      "AttributeError: 'list' object has no attribute 'shape'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-18-639816ee340d>\", line 1, in <module>\n",
      "    print(model.layers.shape)\n",
      "AttributeError: 'list' object has no attribute 'shape'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2895, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3072, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3282, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n"
     ]
    }
   ],
   "source": [
    "\n",
    "\n",
    "for layer in model.layers:\n",
    "    layer.trainable = False\n",
    "\n",
    "model.summary()"
   ]
  },
  {
   "source": [
    "Generar función que agrega capas en la etapa de clasificación"
   ],
   "cell_type": "markdown",
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_fc_layers(model):\n",
    "    \n",
    "    # add new classifier layers\n",
    "    flat = Flatten()(model.layers[-1].output)\n",
    "    dense = Dense(128, activation='relu', kernel_initializer='he_uniform')(flat)\n",
    "    output = Dense(1, activation='sigmoid')(dense)\n",
    "    model = Model(inputs=model.inputs, outputs=output)\n",
    "    \n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "Model: \"model_1\"\n_________________________________________________________________\nLayer (type)                 Output Shape              Param #   \n=================================================================\ninput_1 (InputLayer)         (None, 224, 224, 3)       0         \n_________________________________________________________________\nblock1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      \n_________________________________________________________________\nblock1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     \n_________________________________________________________________\nblock1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         \n_________________________________________________________________\nblock2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     \n_________________________________________________________________\nblock2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    \n_________________________________________________________________\nblock2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         \n_________________________________________________________________\nblock3_conv1 (Conv2D)        (None, 56, 56, 256)       295168    \n_________________________________________________________________\nblock3_conv2 (Conv2D)        (None, 56, 56, 256)       590080    \n_________________________________________________________________\nblock3_conv3 (Conv2D)        (None, 56, 56, 256)       590080    \n_________________________________________________________________\nblock3_pool (MaxPooling2D)   (None, 28, 28, 256)       0         \n_________________________________________________________________\nblock4_conv1 (Conv2D)        (None, 28, 28, 512)       1180160   \n_________________________________________________________________\nblock4_conv2 (Conv2D)        (None, 28, 28, 512)       2359808   \n_________________________________________________________________\nblock4_conv3 (Conv2D)        (None, 28, 28, 512)       2359808   \n_________________________________________________________________\nblock4_pool (MaxPooling2D)   (None, 14, 14, 512)       0         \n_________________________________________________________________\nblock5_conv1 (Conv2D)        (None, 14, 14, 512)       2359808   \n_________________________________________________________________\nblock5_conv2 (Conv2D)        (None, 14, 14, 512)       2359808   \n_________________________________________________________________\nblock5_conv3 (Conv2D)        (None, 14, 14, 512)       2359808   \n_________________________________________________________________\nblock5_pool (MaxPooling2D)   (None, 7, 7, 512)         0         \n_________________________________________________________________\nflatten_1 (Flatten)          (None, 25088)             0         \n_________________________________________________________________\ndense_1 (Dense)              (None, 128)               3211392   \n_________________________________________________________________\ndense_2 (Dense)              (None, 1)                 129       \n=================================================================\nTotal params: 17,926,209\nTrainable params: 3,211,521\nNon-trainable params: 14,714,688\n_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "fullModel = load_fc_layers(model)\n",
    "fullModel.summary()"
   ]
  },
  {
   "source": [
    "Compilar"
   ],
   "cell_type": "markdown",
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "adam = Adam(learning_rate=0.001)\n",
    "\n",
    "fullModel.compile(\n",
    "    optimizer=adam,\n",
    "    loss=binary_crossentropy,\n",
    "    metrics=[accuracy]\n",
    ")"
   ]
  },
  {
   "source": [
    "Entrenar"
   ],
   "cell_type": "markdown",
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "tags": [
     "outputPrepend"
    ]
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "- loss: 0.1441 - accuracy: 0.9125 - val_loss: 0.5324 - val_accuracy: 0.8500\n",
      "Epoch 4/50\n",
      "13/13 [==============================] - 77s 6s/step - loss: 0.1932 - accuracy: 0.9100 - val_loss: 0.0033 - val_accuracy: 0.7500\n",
      "Epoch 5/50\n",
      "13/13 [==============================] - 83s 6s/step - loss: 0.1440 - accuracy: 0.8875 - val_loss: 0.3714 - val_accuracy: 0.7000\n",
      "Epoch 6/50\n",
      "13/13 [==============================] - 79s 6s/step - loss: 0.1282 - accuracy: 0.9175 - val_loss: 0.2837 - val_accuracy: 0.8000\n",
      "Epoch 7/50\n",
      "12/13 [==========================>...] - ETA: 6s - loss: 0.0024 - accuracy: 0.9103 ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-8-847b5e5f2ebc>\", line 6, in <module>\n",
      "    epochs=epoch\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\keras\\engine\\training.py\", line 1147, in fit\n",
      "    initial_epoch=initial_epoch)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\keras\\engine\\training.py\", line 1732, in fit_generator\n",
      "    initial_epoch=initial_epoch)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\keras\\engine\\training_generator.py\", line 220, in fit_generator\n",
      "    reset_metrics=False)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\keras\\engine\\training.py\", line 1514, in train_on_batch\n",
      "    outputs = self.train_function(ins)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow_core\\python\\keras\\backend.py\", line 3740, in __call__\n",
      "    outputs = self._graph_fn(*converted_inputs)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow_core\\python\\eager\\function.py\", line 1081, in __call__\n",
      "    return self._call_impl(args, kwargs)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow_core\\python\\eager\\function.py\", line 1121, in _call_impl\n",
      "    return self._call_flat(args, self.captured_inputs, cancellation_manager)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow_core\\python\\eager\\function.py\", line 1224, in _call_flat\n",
      "    ctx, args, cancellation_manager=cancellation_manager)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow_core\\python\\eager\\function.py\", line 511, in call\n",
      "    ctx=ctx)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow_core\\python\\eager\\execute.py\", line 61, in quick_execute\n",
      "    num_outputs)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-8-847b5e5f2ebc>\", line 6, in <module>\n",
      "    epochs=epoch\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\keras\\engine\\training.py\", line 1147, in fit\n",
      "    initial_epoch=initial_epoch)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\keras\\engine\\training.py\", line 1732, in fit_generator\n",
      "    initial_epoch=initial_epoch)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\keras\\engine\\training_generator.py\", line 220, in fit_generator\n",
      "    reset_metrics=False)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\keras\\engine\\training.py\", line 1514, in train_on_batch\n",
      "    outputs = self.train_function(ins)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow_core\\python\\keras\\backend.py\", line 3740, in __call__\n",
      "    outputs = self._graph_fn(*converted_inputs)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow_core\\python\\eager\\function.py\", line 1081, in __call__\n",
      "    return self._call_impl(args, kwargs)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow_core\\python\\eager\\function.py\", line 1121, in _call_impl\n",
      "    return self._call_flat(args, self.captured_inputs, cancellation_manager)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow_core\\python\\eager\\function.py\", line 1224, in _call_flat\n",
      "    ctx, args, cancellation_manager=cancellation_manager)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow_core\\python\\eager\\function.py\", line 511, in call\n",
      "    ctx=ctx)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow_core\\python\\eager\\execute.py\", line 61, in quick_execute\n",
      "    num_outputs)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-8-847b5e5f2ebc>\", line 6, in <module>\n",
      "    epochs=epoch\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\keras\\engine\\training.py\", line 1147, in fit\n",
      "    initial_epoch=initial_epoch)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\keras\\legacy\\interfaces.py\", line 91, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\keras\\engine\\training.py\", line 1732, in fit_generator\n",
      "    initial_epoch=initial_epoch)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\keras\\engine\\training_generator.py\", line 220, in fit_generator\n",
      "    reset_metrics=False)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\keras\\engine\\training.py\", line 1514, in train_on_batch\n",
      "    outputs = self.train_function(ins)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow_core\\python\\keras\\backend.py\", line 3740, in __call__\n",
      "    outputs = self._graph_fn(*converted_inputs)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow_core\\python\\eager\\function.py\", line 1081, in __call__\n",
      "    return self._call_impl(args, kwargs)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow_core\\python\\eager\\function.py\", line 1121, in _call_impl\n",
      "    return self._call_flat(args, self.captured_inputs, cancellation_manager)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow_core\\python\\eager\\function.py\", line 1224, in _call_flat\n",
      "    ctx, args, cancellation_manager=cancellation_manager)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow_core\\python\\eager\\function.py\", line 511, in call\n",
      "    ctx=ctx)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow_core\\python\\eager\\execute.py\", line 61, in quick_execute\n",
      "    num_outputs)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2895, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3072, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3282, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\vicen\\anaconda3\\envs\\utnia\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n"
     ]
    }
   ],
   "source": [
    "epoch = 50\n",
    "\n",
    "history = fullModel.fit(\n",
    "    train_generator,\n",
    "    validation_data=validation_generator,\n",
    "    epochs=epoch\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "output_type": "display_data",
     "data": {
      "text/plain": "<Figure size 432x288 with 1 Axes>",
      "image/svg+xml": "<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"no\"?>\r\n<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\r\n  \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\r\n<!-- Created with matplotlib (https://matplotlib.org/) -->\r\n<svg height=\"248.518125pt\" version=\"1.1\" viewBox=\"0 0 368.925 248.518125\" width=\"368.925pt\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\r\n <metadata>\r\n  <rdf:RDF xmlns:cc=\"http://creativecommons.org/ns#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">\r\n   <cc:Work>\r\n    <dc:type rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\"/>\r\n    <dc:date>2021-06-22T18:27:17.739162</dc:date>\r\n    <dc:format>image/svg+xml</dc:format>\r\n    <dc:creator>\r\n     <cc:Agent>\r\n      <dc:title>Matplotlib v3.3.4, https://matplotlib.org/</dc:title>\r\n     </cc:Agent>\r\n    </dc:creator>\r\n   </cc:Work>\r\n  </rdf:RDF>\r\n </metadata>\r\n <defs>\r\n  <style type=\"text/css\">*{stroke-linecap:butt;stroke-linejoin:round;}</style>\r\n </defs>\r\n <g id=\"figure_1\">\r\n  <g id=\"patch_1\">\r\n   <path d=\"M -0 248.518125 \r\nL 368.925 248.518125 \r\nL 368.925 0 \r\nL -0 0 \r\nz\r\n\" style=\"fill:none;\"/>\r\n  </g>\r\n  <g id=\"axes_1\">\r\n   <g id=\"patch_2\">\r\n    <path d=\"M 26.925 224.64 \r\nL 361.725 224.64 \r\nL 361.725 7.2 \r\nL 26.925 7.2 \r\nz\r\n\" style=\"fill:#ffffff;\"/>\r\n   </g>\r\n   <g id=\"matplotlib.axis_1\">\r\n    <g id=\"xtick_1\">\r\n     <g id=\"line2d_1\">\r\n      <defs>\r\n       <path d=\"M 0 0 \r\nL 0 3.5 \r\n\" id=\"me378c13817\" style=\"stroke:#000000;stroke-width:0.8;\"/>\r\n      </defs>\r\n      <g>\r\n       <use style=\"stroke:#000000;stroke-width:0.8;\" x=\"42.143182\" xlink:href=\"#me378c13817\" y=\"224.64\"/>\r\n      </g>\r\n     </g>\r\n     <g id=\"text_1\">\r\n      <!-- 0 -->\r\n      <g transform=\"translate(38.961932 239.238438)scale(0.1 -0.1)\">\r\n       <defs>\r\n        <path d=\"M 31.78125 66.40625 \r\nQ 24.171875 66.40625 20.328125 58.90625 \r\nQ 16.5 51.421875 16.5 36.375 \r\nQ 16.5 21.390625 20.328125 13.890625 \r\nQ 24.171875 6.390625 31.78125 6.390625 \r\nQ 39.453125 6.390625 43.28125 13.890625 \r\nQ 47.125 21.390625 47.125 36.375 \r\nQ 47.125 51.421875 43.28125 58.90625 \r\nQ 39.453125 66.40625 31.78125 66.40625 \r\nz\r\nM 31.78125 74.21875 \r\nQ 44.046875 74.21875 50.515625 64.515625 \r\nQ 56.984375 54.828125 56.984375 36.375 \r\nQ 56.984375 17.96875 50.515625 8.265625 \r\nQ 44.046875 -1.421875 31.78125 -1.421875 \r\nQ 19.53125 -1.421875 13.0625 8.265625 \r\nQ 6.59375 17.96875 6.59375 36.375 \r\nQ 6.59375 54.828125 13.0625 64.515625 \r\nQ 19.53125 74.21875 31.78125 74.21875 \r\nz\r\n\" id=\"DejaVuSans-48\"/>\r\n       </defs>\r\n       <use xlink:href=\"#DejaVuSans-48\"/>\r\n      </g>\r\n     </g>\r\n    </g>\r\n    <g id=\"xtick_2\">\r\n     <g id=\"line2d_2\">\r\n      <g>\r\n       <use style=\"stroke:#000000;stroke-width:0.8;\" x=\"104.25821\" xlink:href=\"#me378c13817\" y=\"224.64\"/>\r\n      </g>\r\n     </g>\r\n     <g id=\"text_2\">\r\n      <!-- 10 -->\r\n      <g transform=\"translate(97.89571 239.238438)scale(0.1 -0.1)\">\r\n       <defs>\r\n        <path d=\"M 12.40625 8.296875 \r\nL 28.515625 8.296875 \r\nL 28.515625 63.921875 \r\nL 10.984375 60.40625 \r\nL 10.984375 69.390625 \r\nL 28.421875 72.90625 \r\nL 38.28125 72.90625 \r\nL 38.28125 8.296875 \r\nL 54.390625 8.296875 \r\nL 54.390625 0 \r\nL 12.40625 0 \r\nz\r\n\" id=\"DejaVuSans-49\"/>\r\n       </defs>\r\n       <use xlink:href=\"#DejaVuSans-49\"/>\r\n       <use x=\"63.623047\" xlink:href=\"#DejaVuSans-48\"/>\r\n      </g>\r\n     </g>\r\n    </g>\r\n    <g id=\"xtick_3\">\r\n     <g id=\"line2d_3\">\r\n      <g>\r\n       <use style=\"stroke:#000000;stroke-width:0.8;\" x=\"166.373237\" xlink:href=\"#me378c13817\" y=\"224.64\"/>\r\n      </g>\r\n     </g>\r\n     <g id=\"text_3\">\r\n      <!-- 20 -->\r\n      <g transform=\"translate(160.010737 239.238438)scale(0.1 -0.1)\">\r\n       <defs>\r\n        <path d=\"M 19.1875 8.296875 \r\nL 53.609375 8.296875 \r\nL 53.609375 0 \r\nL 7.328125 0 \r\nL 7.328125 8.296875 \r\nQ 12.9375 14.109375 22.625 23.890625 \r\nQ 32.328125 33.6875 34.8125 36.53125 \r\nQ 39.546875 41.84375 41.421875 45.53125 \r\nQ 43.3125 49.21875 43.3125 52.78125 \r\nQ 43.3125 58.59375 39.234375 62.25 \r\nQ 35.15625 65.921875 28.609375 65.921875 \r\nQ 23.96875 65.921875 18.8125 64.3125 \r\nQ 13.671875 62.703125 7.8125 59.421875 \r\nL 7.8125 69.390625 \r\nQ 13.765625 71.78125 18.9375 73 \r\nQ 24.125 74.21875 28.421875 74.21875 \r\nQ 39.75 74.21875 46.484375 68.546875 \r\nQ 53.21875 62.890625 53.21875 53.421875 \r\nQ 53.21875 48.921875 51.53125 44.890625 \r\nQ 49.859375 40.875 45.40625 35.40625 \r\nQ 44.1875 33.984375 37.640625 27.21875 \r\nQ 31.109375 20.453125 19.1875 8.296875 \r\nz\r\n\" id=\"DejaVuSans-50\"/>\r\n       </defs>\r\n       <use xlink:href=\"#DejaVuSans-50\"/>\r\n       <use x=\"63.623047\" xlink:href=\"#DejaVuSans-48\"/>\r\n      </g>\r\n     </g>\r\n    </g>\r\n    <g id=\"xtick_4\">\r\n     <g id=\"line2d_4\">\r\n      <g>\r\n       <use style=\"stroke:#000000;stroke-width:0.8;\" x=\"228.488265\" xlink:href=\"#me378c13817\" y=\"224.64\"/>\r\n      </g>\r\n     </g>\r\n     <g id=\"text_4\">\r\n      <!-- 30 -->\r\n      <g transform=\"translate(222.125765 239.238438)scale(0.1 -0.1)\">\r\n       <defs>\r\n        <path d=\"M 40.578125 39.3125 \r\nQ 47.65625 37.796875 51.625 33 \r\nQ 55.609375 28.21875 55.609375 21.1875 \r\nQ 55.609375 10.40625 48.1875 4.484375 \r\nQ 40.765625 -1.421875 27.09375 -1.421875 \r\nQ 22.515625 -1.421875 17.65625 -0.515625 \r\nQ 12.796875 0.390625 7.625 2.203125 \r\nL 7.625 11.71875 \r\nQ 11.71875 9.328125 16.59375 8.109375 \r\nQ 21.484375 6.890625 26.8125 6.890625 \r\nQ 36.078125 6.890625 40.9375 10.546875 \r\nQ 45.796875 14.203125 45.796875 21.1875 \r\nQ 45.796875 27.640625 41.28125 31.265625 \r\nQ 36.765625 34.90625 28.71875 34.90625 \r\nL 20.21875 34.90625 \r\nL 20.21875 43.015625 \r\nL 29.109375 43.015625 \r\nQ 36.375 43.015625 40.234375 45.921875 \r\nQ 44.09375 48.828125 44.09375 54.296875 \r\nQ 44.09375 59.90625 40.109375 62.90625 \r\nQ 36.140625 65.921875 28.71875 65.921875 \r\nQ 24.65625 65.921875 20.015625 65.03125 \r\nQ 15.375 64.15625 9.8125 62.3125 \r\nL 9.8125 71.09375 \r\nQ 15.4375 72.65625 20.34375 73.4375 \r\nQ 25.25 74.21875 29.59375 74.21875 \r\nQ 40.828125 74.21875 47.359375 69.109375 \r\nQ 53.90625 64.015625 53.90625 55.328125 \r\nQ 53.90625 49.265625 50.4375 45.09375 \r\nQ 46.96875 40.921875 40.578125 39.3125 \r\nz\r\n\" id=\"DejaVuSans-51\"/>\r\n       </defs>\r\n       <use xlink:href=\"#DejaVuSans-51\"/>\r\n       <use x=\"63.623047\" xlink:href=\"#DejaVuSans-48\"/>\r\n      </g>\r\n     </g>\r\n    </g>\r\n    <g id=\"xtick_5\">\r\n     <g id=\"line2d_5\">\r\n      <g>\r\n       <use style=\"stroke:#000000;stroke-width:0.8;\" x=\"290.603293\" xlink:href=\"#me378c13817\" y=\"224.64\"/>\r\n      </g>\r\n     </g>\r\n     <g id=\"text_5\">\r\n      <!-- 40 -->\r\n      <g transform=\"translate(284.240793 239.238438)scale(0.1 -0.1)\">\r\n       <defs>\r\n        <path d=\"M 37.796875 64.3125 \r\nL 12.890625 25.390625 \r\nL 37.796875 25.390625 \r\nz\r\nM 35.203125 72.90625 \r\nL 47.609375 72.90625 \r\nL 47.609375 25.390625 \r\nL 58.015625 25.390625 \r\nL 58.015625 17.1875 \r\nL 47.609375 17.1875 \r\nL 47.609375 0 \r\nL 37.796875 0 \r\nL 37.796875 17.1875 \r\nL 4.890625 17.1875 \r\nL 4.890625 26.703125 \r\nz\r\n\" id=\"DejaVuSans-52\"/>\r\n       </defs>\r\n       <use xlink:href=\"#DejaVuSans-52\"/>\r\n       <use x=\"63.623047\" xlink:href=\"#DejaVuSans-48\"/>\r\n      </g>\r\n     </g>\r\n    </g>\r\n    <g id=\"xtick_6\">\r\n     <g id=\"line2d_6\">\r\n      <g>\r\n       <use style=\"stroke:#000000;stroke-width:0.8;\" x=\"352.718321\" xlink:href=\"#me378c13817\" y=\"224.64\"/>\r\n      </g>\r\n     </g>\r\n     <g id=\"text_6\">\r\n      <!-- 50 -->\r\n      <g transform=\"translate(346.355821 239.238438)scale(0.1 -0.1)\">\r\n       <defs>\r\n        <path d=\"M 10.796875 72.90625 \r\nL 49.515625 72.90625 \r\nL 49.515625 64.59375 \r\nL 19.828125 64.59375 \r\nL 19.828125 46.734375 \r\nQ 21.96875 47.46875 24.109375 47.828125 \r\nQ 26.265625 48.1875 28.421875 48.1875 \r\nQ 40.625 48.1875 47.75 41.5 \r\nQ 54.890625 34.8125 54.890625 23.390625 \r\nQ 54.890625 11.625 47.5625 5.09375 \r\nQ 40.234375 -1.421875 26.90625 -1.421875 \r\nQ 22.3125 -1.421875 17.546875 -0.640625 \r\nQ 12.796875 0.140625 7.71875 1.703125 \r\nL 7.71875 11.625 \r\nQ 12.109375 9.234375 16.796875 8.0625 \r\nQ 21.484375 6.890625 26.703125 6.890625 \r\nQ 35.15625 6.890625 40.078125 11.328125 \r\nQ 45.015625 15.765625 45.015625 23.390625 \r\nQ 45.015625 31 40.078125 35.4375 \r\nQ 35.15625 39.890625 26.703125 39.890625 \r\nQ 22.75 39.890625 18.8125 39.015625 \r\nQ 14.890625 38.140625 10.796875 36.28125 \r\nz\r\n\" id=\"DejaVuSans-53\"/>\r\n       </defs>\r\n       <use xlink:href=\"#DejaVuSans-53\"/>\r\n       <use x=\"63.623047\" xlink:href=\"#DejaVuSans-48\"/>\r\n      </g>\r\n     </g>\r\n    </g>\r\n   </g>\r\n   <g id=\"matplotlib.axis_2\">\r\n    <g id=\"ytick_1\">\r\n     <g id=\"line2d_7\">\r\n      <defs>\r\n       <path d=\"M 0 0 \r\nL -3.5 0 \r\n\" id=\"m3d94921d5f\" style=\"stroke:#000000;stroke-width:0.8;\"/>\r\n      </defs>\r\n      <g>\r\n       <use style=\"stroke:#000000;stroke-width:0.8;\" x=\"26.925\" xlink:href=\"#m3d94921d5f\" y=\"215.961036\"/>\r\n      </g>\r\n     </g>\r\n     <g id=\"text_7\">\r\n      <!-- 0 -->\r\n      <g transform=\"translate(13.5625 219.760255)scale(0.1 -0.1)\">\r\n       <use xlink:href=\"#DejaVuSans-48\"/>\r\n      </g>\r\n     </g>\r\n    </g>\r\n    <g id=\"ytick_2\">\r\n     <g id=\"line2d_8\">\r\n      <g>\r\n       <use style=\"stroke:#000000;stroke-width:0.8;\" x=\"26.925\" xlink:href=\"#m3d94921d5f\" y=\"169.851812\"/>\r\n      </g>\r\n     </g>\r\n     <g id=\"text_8\">\r\n      <!-- 20 -->\r\n      <g transform=\"translate(7.2 173.651031)scale(0.1 -0.1)\">\r\n       <use xlink:href=\"#DejaVuSans-50\"/>\r\n       <use x=\"63.623047\" xlink:href=\"#DejaVuSans-48\"/>\r\n      </g>\r\n     </g>\r\n    </g>\r\n    <g id=\"ytick_3\">\r\n     <g id=\"line2d_9\">\r\n      <g>\r\n       <use style=\"stroke:#000000;stroke-width:0.8;\" x=\"26.925\" xlink:href=\"#m3d94921d5f\" y=\"123.742588\"/>\r\n      </g>\r\n     </g>\r\n     <g id=\"text_9\">\r\n      <!-- 40 -->\r\n      <g transform=\"translate(7.2 127.541807)scale(0.1 -0.1)\">\r\n       <use xlink:href=\"#DejaVuSans-52\"/>\r\n       <use x=\"63.623047\" xlink:href=\"#DejaVuSans-48\"/>\r\n      </g>\r\n     </g>\r\n    </g>\r\n    <g id=\"ytick_4\">\r\n     <g id=\"line2d_10\">\r\n      <g>\r\n       <use style=\"stroke:#000000;stroke-width:0.8;\" x=\"26.925\" xlink:href=\"#m3d94921d5f\" y=\"77.633364\"/>\r\n      </g>\r\n     </g>\r\n     <g id=\"text_10\">\r\n      <!-- 60 -->\r\n      <g transform=\"translate(7.2 81.432583)scale(0.1 -0.1)\">\r\n       <defs>\r\n        <path d=\"M 33.015625 40.375 \r\nQ 26.375 40.375 22.484375 35.828125 \r\nQ 18.609375 31.296875 18.609375 23.390625 \r\nQ 18.609375 15.53125 22.484375 10.953125 \r\nQ 26.375 6.390625 33.015625 6.390625 \r\nQ 39.65625 6.390625 43.53125 10.953125 \r\nQ 47.40625 15.53125 47.40625 23.390625 \r\nQ 47.40625 31.296875 43.53125 35.828125 \r\nQ 39.65625 40.375 33.015625 40.375 \r\nz\r\nM 52.59375 71.296875 \r\nL 52.59375 62.3125 \r\nQ 48.875 64.0625 45.09375 64.984375 \r\nQ 41.3125 65.921875 37.59375 65.921875 \r\nQ 27.828125 65.921875 22.671875 59.328125 \r\nQ 17.53125 52.734375 16.796875 39.40625 \r\nQ 19.671875 43.65625 24.015625 45.921875 \r\nQ 28.375 48.1875 33.59375 48.1875 \r\nQ 44.578125 48.1875 50.953125 41.515625 \r\nQ 57.328125 34.859375 57.328125 23.390625 \r\nQ 57.328125 12.15625 50.6875 5.359375 \r\nQ 44.046875 -1.421875 33.015625 -1.421875 \r\nQ 20.359375 -1.421875 13.671875 8.265625 \r\nQ 6.984375 17.96875 6.984375 36.375 \r\nQ 6.984375 53.65625 15.1875 63.9375 \r\nQ 23.390625 74.21875 37.203125 74.21875 \r\nQ 40.921875 74.21875 44.703125 73.484375 \r\nQ 48.484375 72.75 52.59375 71.296875 \r\nz\r\n\" id=\"DejaVuSans-54\"/>\r\n       </defs>\r\n       <use xlink:href=\"#DejaVuSans-54\"/>\r\n       <use x=\"63.623047\" xlink:href=\"#DejaVuSans-48\"/>\r\n      </g>\r\n     </g>\r\n    </g>\r\n    <g id=\"ytick_5\">\r\n     <g id=\"line2d_11\">\r\n      <g>\r\n       <use style=\"stroke:#000000;stroke-width:0.8;\" x=\"26.925\" xlink:href=\"#m3d94921d5f\" y=\"31.52414\"/>\r\n      </g>\r\n     </g>\r\n     <g id=\"text_11\">\r\n      <!-- 80 -->\r\n      <g transform=\"translate(7.2 35.323359)scale(0.1 -0.1)\">\r\n       <defs>\r\n        <path d=\"M 31.78125 34.625 \r\nQ 24.75 34.625 20.71875 30.859375 \r\nQ 16.703125 27.09375 16.703125 20.515625 \r\nQ 16.703125 13.921875 20.71875 10.15625 \r\nQ 24.75 6.390625 31.78125 6.390625 \r\nQ 38.8125 6.390625 42.859375 10.171875 \r\nQ 46.921875 13.96875 46.921875 20.515625 \r\nQ 46.921875 27.09375 42.890625 30.859375 \r\nQ 38.875 34.625 31.78125 34.625 \r\nz\r\nM 21.921875 38.8125 \r\nQ 15.578125 40.375 12.03125 44.71875 \r\nQ 8.5 49.078125 8.5 55.328125 \r\nQ 8.5 64.0625 14.71875 69.140625 \r\nQ 20.953125 74.21875 31.78125 74.21875 \r\nQ 42.671875 74.21875 48.875 69.140625 \r\nQ 55.078125 64.0625 55.078125 55.328125 \r\nQ 55.078125 49.078125 51.53125 44.71875 \r\nQ 48 40.375 41.703125 38.8125 \r\nQ 48.828125 37.15625 52.796875 32.3125 \r\nQ 56.78125 27.484375 56.78125 20.515625 \r\nQ 56.78125 9.90625 50.3125 4.234375 \r\nQ 43.84375 -1.421875 31.78125 -1.421875 \r\nQ 19.734375 -1.421875 13.25 4.234375 \r\nQ 6.78125 9.90625 6.78125 20.515625 \r\nQ 6.78125 27.484375 10.78125 32.3125 \r\nQ 14.796875 37.15625 21.921875 38.8125 \r\nz\r\nM 18.3125 54.390625 \r\nQ 18.3125 48.734375 21.84375 45.5625 \r\nQ 25.390625 42.390625 31.78125 42.390625 \r\nQ 38.140625 42.390625 41.71875 45.5625 \r\nQ 45.3125 48.734375 45.3125 54.390625 \r\nQ 45.3125 60.0625 41.71875 63.234375 \r\nQ 38.140625 66.40625 31.78125 66.40625 \r\nQ 25.390625 66.40625 21.84375 63.234375 \r\nQ 18.3125 60.0625 18.3125 54.390625 \r\nz\r\n\" id=\"DejaVuSans-56\"/>\r\n       </defs>\r\n       <use xlink:href=\"#DejaVuSans-56\"/>\r\n       <use x=\"63.623047\" xlink:href=\"#DejaVuSans-48\"/>\r\n      </g>\r\n     </g>\r\n    </g>\r\n   </g>\r\n   <g id=\"line2d_12\">\r\n    <path clip-path=\"url(#p04a15aff7c)\" d=\"M 42.143182 17.083636 \r\nL 48.354685 214.112525 \r\nL 54.566187 214.35263 \r\nL 60.77769 214.36037 \r\nL 66.989193 214.361519 \r\nL 73.200696 214.406701 \r\nL 79.412199 214.396423 \r\nL 85.623701 214.385717 \r\nL 91.835204 214.420336 \r\nL 98.046707 214.424315 \r\nL 104.25821 214.4517 \r\nL 110.469712 214.424566 \r\nL 116.681215 214.455659 \r\nL 122.892718 214.482625 \r\nL 129.104221 214.427512 \r\nL 135.315724 214.462418 \r\nL 141.527226 214.467045 \r\nL 147.738729 214.448709 \r\nL 153.950232 214.47036 \r\nL 160.161735 214.450972 \r\nL 166.373237 214.47902 \r\nL 172.58474 214.343946 \r\nL 178.796243 214.426895 \r\nL 185.007746 214.481522 \r\nL 191.219249 214.485943 \r\nL 197.430751 214.542128 \r\nL 203.642254 214.545437 \r\nL 209.853757 214.477633 \r\nL 216.06526 214.531913 \r\nL 222.276763 214.627166 \r\nL 228.488265 214.511609 \r\nL 234.699768 214.419784 \r\nL 240.911271 214.453546 \r\nL 247.122774 214.511312 \r\nL 253.334276 214.52515 \r\nL 259.545779 214.235469 \r\nL 265.757282 214.576508 \r\nL 271.968785 214.631396 \r\nL 278.180288 214.461521 \r\nL 284.39179 214.597781 \r\nL 290.603293 214.592494 \r\nL 296.814796 214.756364 \r\nL 303.026299 214.751307 \r\nL 309.237801 214.696159 \r\nL 315.449304 214.730289 \r\nL 321.660807 214.688259 \r\nL 327.87231 214.540501 \r\nL 334.083813 214.561088 \r\nL 340.295315 214.578095 \r\nL 346.506818 214.587886 \r\n\" style=\"fill:none;stroke:#ff0000;stroke-linecap:square;stroke-width:1.5;\"/>\r\n   </g>\r\n   <g id=\"line2d_13\">\r\n    <path clip-path=\"url(#p04a15aff7c)\" d=\"M 42.143182 214.195361 \r\nL 48.354685 214.335615 \r\nL 54.566187 214.40276 \r\nL 60.77769 214.355742 \r\nL 66.989193 214.30755 \r\nL 73.200696 214.320665 \r\nL 79.412199 214.270677 \r\nL 85.623701 214.342325 \r\nL 91.835204 214.347789 \r\nL 98.046707 214.122156 \r\nL 104.25821 214.283351 \r\nL 110.469712 213.998168 \r\nL 116.681215 214.264314 \r\nL 122.892718 214.197702 \r\nL 129.104221 214.018863 \r\nL 135.315724 214.210365 \r\nL 141.527226 214.294356 \r\nL 147.738729 214.308777 \r\nL 153.950232 213.591689 \r\nL 160.161735 214.287307 \r\nL 166.373237 213.949768 \r\nL 172.58474 213.933436 \r\nL 178.796243 214.136389 \r\nL 185.007746 213.867702 \r\nL 191.219249 214.210853 \r\nL 197.430751 213.772962 \r\nL 203.642254 214.056849 \r\nL 209.853757 214.15853 \r\nL 216.06526 214.175083 \r\nL 222.276763 213.888893 \r\nL 228.488265 214.010327 \r\nL 234.699768 214.062092 \r\nL 240.911271 213.901015 \r\nL 247.122774 213.868053 \r\nL 253.334276 213.748318 \r\nL 259.545779 214.379925 \r\nL 265.757282 214.453893 \r\nL 271.968785 214.03541 \r\nL 278.180288 214.025124 \r\nL 284.39179 214.376384 \r\nL 290.603293 214.290754 \r\nL 296.814796 214.438585 \r\nL 303.026299 213.088675 \r\nL 309.237801 214.205297 \r\nL 315.449304 214.115203 \r\nL 321.660807 213.253646 \r\nL 327.87231 214.297459 \r\nL 334.083813 214.239712 \r\nL 340.295315 213.884785 \r\nL 346.506818 214.429863 \r\n\" style=\"fill:none;stroke:#0000ff;stroke-linecap:square;stroke-width:1.5;\"/>\r\n   </g>\r\n   <g id=\"patch_3\">\r\n    <path d=\"M 26.925 224.64 \r\nL 26.925 7.2 \r\n\" style=\"fill:none;stroke:#000000;stroke-linecap:square;stroke-linejoin:miter;stroke-width:0.8;\"/>\r\n   </g>\r\n   <g id=\"patch_4\">\r\n    <path d=\"M 361.725 224.64 \r\nL 361.725 7.2 \r\n\" style=\"fill:none;stroke:#000000;stroke-linecap:square;stroke-linejoin:miter;stroke-width:0.8;\"/>\r\n   </g>\r\n   <g id=\"patch_5\">\r\n    <path d=\"M 26.925 224.64 \r\nL 361.725 224.64 \r\n\" style=\"fill:none;stroke:#000000;stroke-linecap:square;stroke-linejoin:miter;stroke-width:0.8;\"/>\r\n   </g>\r\n   <g id=\"patch_6\">\r\n    <path d=\"M 26.925 7.2 \r\nL 361.725 7.2 \r\n\" style=\"fill:none;stroke:#000000;stroke-linecap:square;stroke-linejoin:miter;stroke-width:0.8;\"/>\r\n   </g>\r\n  </g>\r\n </g>\r\n <defs>\r\n  <clipPath id=\"p04a15aff7c\">\r\n   <rect height=\"217.44\" width=\"334.8\" x=\"26.925\" y=\"7.2\"/>\r\n  </clipPath>\r\n </defs>\r\n</svg>\r\n",
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXAAAAD4CAYAAAD1jb0+AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAU1ElEQVR4nO3dbYxc133f8e//zuzuDHdJipJI6tmUY/lBTmSrIRq5Ltokils3NiK9MeAALojCgIAgbZ02QSDnRd0UCCogRZC8KBoIdloBcVMIjlOpQuBGYGK0fmE3lJ9l2pUfZEkVJdKWxCWXuzs7M/++uHeXwydzuQ9cnp3vBzg4d+7O3Pmf2Zkfz5zlzI3MRJJUnmqrC5AkrY0BLkmFMsAlqVAGuCQVygCXpEK1r+ad3XjjjXngwIGreZeSVLxnnnnmR5m59/z9VzXADxw4wJEjR67mXUpS8SLihxfb7xKKJBXKAJekQhngklQoA1ySCmWAS1KhDHBJKpQBLkmFKiPAn3oKHnlkq6uQpGtKGQH+uc/B7//+VlchSdeUMgK804GFha2uQpKuKWUEeLdbB7hnD5KkFWUEeKcDwyH0+1tdiSRdM8oJcHAZRZJGGOCSVCgDXJIKZYBLUqEMcEkqlAEuSYUqK8Dn57e2Dkm6hpQV4M7AJWnFqgI8Iv5VRDwbEd+MiD+LiE5EXB8RT0fEc02/Z9OqNMAl6QKXDfCIuBX4l8DBzPxpoAV8GHgYOJyZdwGHm8ubwwCXpAusdgmlDXQjog3sAF4GHgAea37+GPDghle3zACXpAtcNsAz8/8B/wF4ATgGnMzMvwL2Z+ax5jrHgH0Xu31EPBQRRyLiyIkTJ9ZWpQEuSRdYzRLKHurZ9p3ALcB0RHxktXeQmY9m5sHMPLh37961VWmAS9IFVrOE8kvADzLzRGYuAZ8F/h7wakTcDND0xzetym637g1wSVqxmgB/AbgvInZERAD3A0eBJ4FDzXUOAU9sTonA1FTdG+CStKJ9uStk5pci4jPAl4E+8BXgUWAGeDwiPkod8h/atCpbLZiYMMAlacRlAxwgMz8BfOK83YvUs/Grw9OqSdI5yvgkJhjgknQeA1ySCmWAS1KhDHBJKlRZAe7XyUrSirIC3Bm4JK0wwCWpUAa4JBXKAJekQhngklSocgK82zXAJWlEOQHuDFySzmGAS1KhygvwzK2uRJKuCWUFOECvt7V1SNI1orwAdxlFkgADXJKKZYBLUqEMcEkqVHkB7lfKShJQYoA7A5ckwACXpGIZ4JJUKANckgpVToB3u3VvgEsSUFKAOwOXpHMY4JJUKANckgplgEtSocoJ8KmpujfAJQkoKcAj6hA3wCUJKCnAwdOqSdIIA1ySClVegPtthJIElBjgzsAlCTDAJalYBrgkFWpVAR4R10XEZyLi2xFxNCLeExHXR8TTEfFc0+/Z7GINcEk6a7Uz8D8CPpeZbwfeBRwFHgYOZ+ZdwOHm8uYywCVpxWUDPCJ2Af8A+BRAZvYy8w3gAeCx5mqPAQ9uTokjul0DXJIaq5mBvxk4AfzniPhKRHwyIqaB/Zl5DKDp913sxhHxUEQciYgjJ06cWF+1zsAlacVqArwN/B3gP2XmvcAcV7BckpmPZubBzDy4d+/eNZbZMMAlacVqAvwl4KXM/FJz+TPUgf5qRNwM0PTHN6fEEQa4JK24bIBn5ivAixHxtmbX/cC3gCeBQ82+Q8ATm1LhKANckla0V3m9fwF8OiImge8D/4w6/B+PiI8CLwAf2pwSRxjgkrRiVQGemV8FDl7kR/dvaDWX0+lArwfDIVRlfQZJkjZaWSm4fFaexcWtrUOSrgFlBrjLKJJUaID7lbKSVGiAOwOXJANckkplgEtSoQxwSSpUWQHe7da9AS5JhQW4M3BJWmGAS1KhDHBJKpQBLkmFMsAlqVAGuCQVygCXpEKVFeATExBhgEsSpQV4hGflkaRGWQEOdYD7dbKSVGiAOwOXJANckkplgEtSocoL8G7XAJckSgxwZ+CSBBjgklQsA1ySCmWAS1KhDHBJKpQBLkmFMsAlqVAGuCQVygCXpEKVGeD9ft0kaYyVGeDgLFzS2DPAJalQBrgkFcoAl6RClRfg3W7dG+CSxtyqAzwiWhHxlYh4qrl8fUQ8HRHPNf2ezStzhDNwSQKubAb+MeDoyOWHgcOZeRdwuLm8+QxwSQJWGeARcRvwAeCTI7sfAB5rth8DHtzQyi7FAJckYPUz8D8EfhsYjuzbn5nHAJp+38VuGBEPRcSRiDhy4sSJ9dRaM8AlCVhFgEfEB4HjmfnMWu4gMx/NzIOZeXDv3r1rOcS5DHBJAqC9iuu8F/iViPhloAPsiog/BV6NiJsz81hE3Awc38xCVxjgkgSsYgaemR/PzNsy8wDwYeCvM/MjwJPAoeZqh4AnNq3KUQa4JAHr+3/gjwDvi4jngPc1lzefAS5JwOqWUFZk5ueBzzfbPwbu3/iSLsMAlySgxE9iLgf4/PzW1iFJW6y8AG+3odVyBi5p7JUX4OBZeSQJA1ySilVmgHe7BriksVdmgDsDlyQDXJJKZYBLUqEMcEkqlAEuSYUywCWpUAa4JBXKAJekQhngklQoA1ySClVugPt1spLGXLkBvrAAmVtdiSRtmXIDPBOWlra6EknaMmUGeLdb966DSxpjZQa458WUJANckkplgEtSoQxwSSqUAS5JhTLAJalQBrgkFcoAl6RCGeCSVCgDXJIKZYBLUqHKDnC/UlbSGCs7wJ2BSxpjBrgkFarMAK8qmJw0wCWNtTIDHDwvpqSxZ4BLUqEMcEkq1GUDPCJuj4i/iYijEfFsRHys2X99RDwdEc81/Z7NL3eEAS5pzK1mBt4HfjMz3wHcB/x6RNwNPAwczsy7gMPN5avHAJc05i4b4Jl5LDO/3GyfAo4CtwIPAI81V3sMeHCTarw4A1zSmLuiNfCIOADcC3wJ2J+Zx6AOeWDfJW7zUEQciYgjJ06cWGe5IwxwSWNu1QEeETPAnwO/kZmzq71dZj6amQcz8+DevXvXUuPFGeCSxtyqAjwiJqjD+9OZ+dlm96sRcXPz85uB45tT4iUY4JLG3Gr+F0oAnwKOZuYfjPzoSeBQs30IeGLjy/sJDHBJY669iuu8F/inwDci4qvNvt8BHgEej4iPAi8AH9qUCi/FAJc05i4b4Jn5BSAu8eP7N7acK9Dp+HWyksaan8SUpEKVG+DdrgEuaayVG+CdDiwuQuZWVyJJW6LsAIc6xCVpDJUf4C6jSBpTBrgkFcoAl6RCGeCSVCgDXJIKZYBLUqEMcEkqlAEuSYUywCWpUAa4JBWq/AD3K2UljalyA7zbrXtn4JLGVLkB7hKKpDFngEtSocoN8MnJujfAJY2pcgM8wtOqSRpr5QY4GOCSxpoBLkmFMsAlqVAGuCQVygCXpEIZ4JJUKANckgplgEtSocoPcL+NUNKYKj/AnYFLGlNlB3i3a4BLGltlB7gzcEljzACXpEIZ4JJUqPIDfGkJBoOtrkSSrrryAxxgcXFr65CkLdDe6gLWZfS0ajt2bG0tkjZdvw/PPgtf/GI9b/uZn4F77oEbbrjyY83Nwfe+B88/DzfdBHffDTMzG17yplpXgEfE+4E/AlrAJzPzkQ2p6jxf+AJ85zswMVGfSW25TXzvLUzwC7R+63/QuvE6Wt0pqu4UrR11S4JhBsMhDKnqPkf2ndcTUbeqIqp6e7kfDjmnDQaQCVWVtCpoVUmrStqtpNWCIKGqzh6zab1+xfxixZn5YH6xYn4xODNfMcxgaiqZnGCkrw8xdyY4PRdn+/mK+YWgM5VM7zi37diRRASDYd2G2WxnsLQEC/OwuJgsLjbbPRgOoNNJOlOjfV1HqxX1uNrQalH3VdbjAyKSgPrBAI7/uMWLx9q8cGyi6du8eKxNBNx2U5/bb+5z+039ZnuJ3TNDTp1pcWquYnauxexcxezpitNzFcNB/WDnIGE4qPscMjWRdDrQmUq63brWTgeWhi3mFirm5lvMLbSYm6+Ym6+IgF07k10zQ3btTHbvHLJr55CJCXjtZKtub7R47WTFa69XzJ4Ouh2YmUlmput+egfMTCeTE0m7GtJuDWlXQyZaQ9oxpGqdfb5EKyDq59DSoOL0fF3T6TMVp+eC06frOUe7DRPtZLI9ZKJdH2uiGtKqhlSMtKz7pX6wuFTR6weLvbN9fxhk87xe/s0MMxgMgqV+0O/DUj9Y6tcrjhFw0w1L3HL9Irdcd4Zbdp7ilumT3NQ9ydTOSVq7ps9tu2c4vTjB629E3V6H116D119v/gSVSfYHMBis9O1qyK7rgl27K3bvqdi1p8XuG9pM76ya2uowXu6Hw/rxGH19T03V+557rg7sL34Rjhypg/d8t9xSB/k998Cb31w/HUePPxjUn/n7wQ/gu9+tg/uVVy48zpveBO98Z/LOtw+5+619btgzYDCIldwYDOrHdmExmD0VnJyF2dng5Gwwe6r+R+XGG2H/Pti3v+733xTs2wd33gk7pmNDszGyeeFd8Q0jWsD/Bd4HvAT8LfCrmfmtS93m4MGDeeTIkSu+r1/7NfjjP15TmdvSNKfpsMACHc6wg1zjStgEPTosECSLTLFIZ8Nq3M8r3M6L3MEL3M6LJMFL3MaL3M6L3M6r7L9o3V3OsItZppmjYnj2HwrOPk97TDJPlwU6LNA5p+5JFplm7pyWBLPsWmnnj7PLGa7ntZW2k1Ms0GGOaU4zw2lmVraXmGCJySt+PJbrmmmOOBU9+tlqjnduOy++V1qbPlMsMkmPqeY3NkmPNn2CXHm8lvsWAyZYok3/nHsYUvEKN/Eyt3CMm9c0HoA2S3SZv+B3FCRLTDDHxk1nJ1ji3s63+Lnu17mv8zXu636Naeb4+sJb67b4Nr7eexvfWrqLHlOXPM6trWO8pf1Dfqr9PG9p/YCfqp7nTdWLvNK7nmd7d/Fs/608O3wH3+btq3497GCO3ZxkF7NM0uNH3Mhx9jE4b3781O8+wwf+zc+uafwR8UxmHrxg/zoC/D3Av83Mf9xc/jhAZv77S91mrQF+8iTMzkKvV88ger2zbenMEoO5BQZnFhku9BicWazbfI8qkqpKKpKqgirq+UmrOnt5ZX9A5LCeTQzrmV4OEkhyUM+qq0iqVqzcLoKzM9xhMMiKwTDoD6KeApzXcjhksj2kOzlgx+SAbtN2TA2oclDPrpaCxV4901pcqt81zHT6THeHzHSb6zazveVa5xeinnE2s06AVgxXWsWwfjFP1LPWqSmYmkyqdlVPq+tfHMNB0uvBQq9iYTFY6FVnx9RnZYz9PhDLs716RpFRkQQ37lzgtuvm6EwMzh1/xPITp34nMmjx8hs7mD3TZlenx65Oj51TPSZazVscOPct1/J2u10fb2RqNVwasLgwpM2AiaqeAV7wlmnE4lLF7MIkS0uwpzNPt7107m0u9Ufx+i0XWbUYVm36tFdiMQlyMCRX3jXUz6XWcImZ1jyT9Op6l9tgUI9pYqKZip+33W6f20Z+TwyHZ/vR7eUxjI5l+TajfUS9VjAzw3DHDD8e7uHlM9fxyqlpeqd7DE7P121uvn5tzS0yXc2zZ+oM10/NsWeybtPVPNFu1VPl81urxWCxz6nZ5OSp+l3NyVP187OK+l1Mq2r65nna7w3pLQzpLSa9xSG9hfqd4h07TnDvdc/TaS2dfR4tj6PVqt+mNm0pJjk+v5MWA9oxqHv6K22inedcf+Xd8ei0f3KSfmuK75/ay6mlTv36qXLln9JWDJms+uyeWmDX1CLtanjBYzwcJK8vdHn11A6Oz03z6twM//Bf/yw3vefOK42/ZqgXD/D1LKHcCrw4cvkl4OcucscPAQ8B3HHHHWu6o92763ZxE03buaZjX0um13CbAHY0be86778COk3bbJPAgQ06VgV0r+D6U6zvsQrqNcNWc6ySVdSPxV7gXRt87BZwXdOulgnqYFqvNvDWddy+Am5o2t0bUM9Pup+1uthizgXT+cx8NDMPZubBvXvXGzGSpGXrCfCXgNtHLt8GvLy+ciRJq7WeAP9b4K6IuDMiJoEPA09uTFmSpMtZ8xp4ZvYj4p8D/5N6uetPMvPZDatMkvQTrev/gWfmXwJ/uUG1SJKuQNkfpZekMWaAS1KhDHBJKtSaP4m5pjuLOAH8cI03vxH40QaWUwrHPX7GdeyO+9LelJkXfJDmqgb4ekTEkYt9lHS7c9zjZ1zH7rivnEsoklQoA1ySClVSgD+61QVsEcc9fsZ17I77ChWzBi5JOldJM3BJ0ggDXJIKVUSAR8T7I+I7EfHdiHh4q+vZLBHxJxFxPCK+ObLv+oh4OiKea/o9W1njZoiI2yPibyLiaEQ8GxEfa/Zv67FHRCci/k9EfK0Z9+82+7f1uJdFRCsivhIRTzWXt/24I+L5iPhGRHw1Io40+9Y87ms+wJtzb/5H4J9Qn9ziVyNiM09ysZX+C/D+8/Y9DBzOzLuAw83l7aYP/GZmvgO4D/j15ne83ce+CPxiZr4LeDfw/oi4j+0/7mUfA46OXB6Xcf9CZr575P9+r3nc13yAA38X+G5mfj8ze8B/Ax7Y4po2RWb+L+C183Y/ADzWbD8GPHg1a7oaMvNYZn652T5F/aK+lW0+9qydbi4unxsw2ebjBoiI24APAJ8c2b3tx30Jax53CQF+sXNvbsRp70qxPzOPQR10wL4trmdTRcQB4F7gS4zB2JtlhK8Cx4GnM3Msxg38IfDbwOgZp8dh3An8VUQ805wvGNYx7nV9H/hVsqpzb6p8ETED/DnwG5k5G3GxX/32kpkD4N0RcR3wFxHx01tc0qaLiA8CxzPzmYj4+S0u52p7b2a+HBH7gKcj4tvrOVgJM/BxP/fmqxFxM0DTH9/iejZFRExQh/enM/Ozze6xGDtAZr4BfJ76byDbfdzvBX4lIp6nXhL9xYj4U7b/uMnMl5v+OPAX1EvEax53CQE+7ufefBI41GwfAp7Ywlo2RdRT7U8BRzPzD0Z+tK3HHhF7m5k3EdEFfgn4Ntt83Jn58cy8LTMPUL+e/zozP8I2H3dETEfEzuVt4B8B32Qd4y7ik5gR8cvUa2bL5978va2taHNExJ8BP0/99ZKvAp8A/jvwOHAH8ALwocw8/w+dRYuIvw/8b+AbnF0T/R3qdfBtO/aIuIf6j1Yt6snU45n57yLiBrbxuEc1Syi/lZkf3O7jjog3U8+6oV6+/q+Z+XvrGXcRAS5JulAJSyiSpIswwCWpUAa4JBXKAJekQhngklQoA1ySCmWAS1Kh/j+g4lPTsP4OFQAAAABJRU5ErkJggg==\n"
     },
     "metadata": {
      "needs_background": "light"
     }
    }
   ],
   "source": [
    "history.history\n",
    "plt.plot(range(len(history.history['loss'])), history.history['loss'], color='red')\n",
    "plt.plot(range(len(history.history['val_loss'])), history.history['val_loss'], color='blue')\n",
    "\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "name": "python3",
   "display_name": "Python 3.6.13 64-bit ('utnia': conda)"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.13"
  },
  "interpreter": {
   "hash": "4b4807b60bda7231d5ec54d8119b2f2a568e48627af66bde43e1abe2d4225a0c"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}